# Generated by Django 6.0.5 on 2026-05-18 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia_id', models.CharField(max_length=255)),
                ('periodo_id', models.CharField(max_length=255)),
                ('promedio_grupo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tasa_aprobacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tasa_asistencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_alumnos', models.IntegerField()),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estadisticas_snapshot',
            },
        ),
        migrations.CreateModel(
            name='ReporteCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia_id', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('calificaciones', 'Calificaciones'), ('asistencia', 'Asistencia'), ('rendimiento', 'Rendimiento')], max_length=20)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('xls', 'Excel (XLS)'), ('xlsx', 'Excel (XLSX)')], max_length=10)),
                ('archivo_path', models.CharField(max_length=500)),
                ('generado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('valido_hasta', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes_cache',
            },
        ),
    ]
