# Generated by Django 5.1 on 2026-05-07 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alumno_id', models.UUIDField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='calificaciones', to='actividades.actividad')),
            ],
            options={
                'db_table': 'calificacion',
                'constraints': [models.UniqueConstraint(fields=('actividad', 'alumno_id'), name='unique_calificacion_por_alumno_actividad')],
            },
        ),
    ]
