# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import alumnos_pb2 as alumnos__pb2


class AlumnosServiceStub(object):
    """---------------------------------------------------------------------------
    Servicio gRPC expuesto por MS-3 para consumo de otros microservicios
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAlumnosByMateria = channel.unary_unary(
                '/alumnos.AlumnosService/GetAlumnosByMateria',
                request_serializer=alumnos__pb2.GetAlumnosByMateriaRequest.SerializeToString,
                response_deserializer=alumnos__pb2.GetAlumnosByMateriaResponse.FromString,
                )
        self.GetAlumnoById = channel.unary_unary(
                '/alumnos.AlumnosService/GetAlumnoById',
                request_serializer=alumnos__pb2.GetAlumnoByIdRequest.SerializeToString,
                response_deserializer=alumnos__pb2.AlumnoInfo.FromString,
                )
        self.IsAlumnoEnMateria = channel.unary_unary(
                '/alumnos.AlumnosService/IsAlumnoEnMateria',
                request_serializer=alumnos__pb2.IsAlumnoEnMateriaRequest.SerializeToString,
                response_deserializer=alumnos__pb2.IsAlumnoEnMateriaResponse.FromString,
                )
        self.GetDocenteById = channel.unary_unary(
                '/alumnos.AlumnosService/GetDocenteById',
                request_serializer=alumnos__pb2.GetDocenteByIdRequest.SerializeToString,
                response_deserializer=alumnos__pb2.DocenteInfo.FromString,
                )
        self.GetDocenteByName = channel.unary_unary(
                '/alumnos.AlumnosService/GetDocenteByName',
                request_serializer=alumnos__pb2.GetDocenteByNameRequest.SerializeToString,
                response_deserializer=alumnos__pb2.DocenteInfo.FromString,
                )


class AlumnosServiceServicer(object):
    """---------------------------------------------------------------------------
    Servicio gRPC expuesto por MS-3 para consumo de otros microservicios
    ---------------------------------------------------------------------------
    """

    def GetAlumnosByMateria(self, request, context):
        """Obtener lista de alumnos inscritos (activos) en una materia
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlumnoById(self, request, context):
        """Obtener información completa de un alumno por su ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAlumnoEnMateria(self, request, context):
        """Verificar si un alumno está inscrito y activo en una materia
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocenteById(self, request, context):
        """Obtener información de un docente por su ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocenteByName(self, request, context):
        """Obtener información de un docente por su nombre completo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlumnosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAlumnosByMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlumnosByMateria,
                    request_deserializer=alumnos__pb2.GetAlumnosByMateriaRequest.FromString,
                    response_serializer=alumnos__pb2.GetAlumnosByMateriaResponse.SerializeToString,
            ),
            'GetAlumnoById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlumnoById,
                    request_deserializer=alumnos__pb2.GetAlumnoByIdRequest.FromString,
                    response_serializer=alumnos__pb2.AlumnoInfo.SerializeToString,
            ),
            'IsAlumnoEnMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAlumnoEnMateria,
                    request_deserializer=alumnos__pb2.IsAlumnoEnMateriaRequest.FromString,
                    response_serializer=alumnos__pb2.IsAlumnoEnMateriaResponse.SerializeToString,
            ),
            'GetDocenteById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocenteById,
                    request_deserializer=alumnos__pb2.GetDocenteByIdRequest.FromString,
                    response_serializer=alumnos__pb2.DocenteInfo.SerializeToString,
            ),
            'GetDocenteByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocenteByName,
                    request_deserializer=alumnos__pb2.GetDocenteByNameRequest.FromString,
                    response_serializer=alumnos__pb2.DocenteInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alumnos.AlumnosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AlumnosService(object):
    """---------------------------------------------------------------------------
    Servicio gRPC expuesto por MS-3 para consumo de otros microservicios
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def GetAlumnosByMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alumnos.AlumnosService/GetAlumnosByMateria',
            alumnos__pb2.GetAlumnosByMateriaRequest.SerializeToString,
            alumnos__pb2.GetAlumnosByMateriaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAlumnoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alumnos.AlumnosService/GetAlumnoById',
            alumnos__pb2.GetAlumnoByIdRequest.SerializeToString,
            alumnos__pb2.AlumnoInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsAlumnoEnMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alumnos.AlumnosService/IsAlumnoEnMateria',
            alumnos__pb2.IsAlumnoEnMateriaRequest.SerializeToString,
            alumnos__pb2.IsAlumnoEnMateriaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDocenteById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alumnos.AlumnosService/GetDocenteById',
            alumnos__pb2.GetDocenteByIdRequest.SerializeToString,
            alumnos__pb2.DocenteInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDocenteByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/alumnos.AlumnosService/GetDocenteByName',
            alumnos__pb2.GetDocenteByNameRequest.SerializeToString,
            alumnos__pb2.DocenteInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
