# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alumnos.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ralumnos.proto\x12\x07\x61lumnos\"l\n\nAlumnoInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tmatricula\x18\x02 \x01(\t\x12\x17\n\x0fnombre_completo\x18\x03 \x01(\t\x12\x0e\n\x06\x63orreo\x18\x04 \x01(\t\x12\x16\n\x0etipo_formacion\x18\x05 \x01(\t\"0\n\x1aGetAlumnosByMateriaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"R\n\x1bGetAlumnosByMateriaResponse\x12$\n\x07\x61lumnos\x18\x01 \x03(\x0b\x32\x13.alumnos.AlumnoInfo\x12\r\n\x05total\x18\x02 \x01(\x05\")\n\x14GetAlumnoByIdRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\"A\n\x18IsAlumnoEnMateriaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\"=\n\x19IsAlumnoEnMateriaResponse\x12\x10\n\x08inscrito\x18\x01 \x01(\x08\x12\x0e\n\x06\x61\x63tivo\x18\x02 \x01(\x08\"b\n\x0b\x44ocenteInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fnombre_completo\x18\x02 \x01(\t\x12\x1c\n\x14\x63orreo_institucional\x18\x03 \x01(\t\x12\x10\n\x08\x63ubiculo\x18\x04 \x01(\t\"+\n\x15GetDocenteByIdRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\t\"2\n\x17GetDocenteByNameRequest\x12\x17\n\x0fnombre_completo\x18\x01 \x01(\t2\xa7\x03\n\x0e\x41lumnosService\x12`\n\x13GetAlumnosByMateria\x12#.alumnos.GetAlumnosByMateriaRequest\x1a$.alumnos.GetAlumnosByMateriaResponse\x12\x43\n\rGetAlumnoById\x12\x1d.alumnos.GetAlumnoByIdRequest\x1a\x13.alumnos.AlumnoInfo\x12Z\n\x11IsAlumnoEnMateria\x12!.alumnos.IsAlumnoEnMateriaRequest\x1a\".alumnos.IsAlumnoEnMateriaResponse\x12\x46\n\x0eGetDocenteById\x12\x1e.alumnos.GetDocenteByIdRequest\x1a\x14.alumnos.DocenteInfo\x12J\n\x10GetDocenteByName\x12 .alumnos.GetDocenteByNameRequest\x1a\x14.alumnos.DocenteInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alumnos_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ALUMNOINFO']._serialized_start=26
  _globals['_ALUMNOINFO']._serialized_end=134
  _globals['_GETALUMNOSBYMATERIAREQUEST']._serialized_start=136
  _globals['_GETALUMNOSBYMATERIAREQUEST']._serialized_end=184
  _globals['_GETALUMNOSBYMATERIARESPONSE']._serialized_start=186
  _globals['_GETALUMNOSBYMATERIARESPONSE']._serialized_end=268
  _globals['_GETALUMNOBYIDREQUEST']._serialized_start=270
  _globals['_GETALUMNOBYIDREQUEST']._serialized_end=311
  _globals['_ISALUMNOENMATERIAREQUEST']._serialized_start=313
  _globals['_ISALUMNOENMATERIAREQUEST']._serialized_end=378
  _globals['_ISALUMNOENMATERIARESPONSE']._serialized_start=380
  _globals['_ISALUMNOENMATERIARESPONSE']._serialized_end=441
  _globals['_DOCENTEINFO']._serialized_start=443
  _globals['_DOCENTEINFO']._serialized_end=541
  _globals['_GETDOCENTEBYIDREQUEST']._serialized_start=543
  _globals['_GETDOCENTEBYIDREQUEST']._serialized_end=586
  _globals['_GETDOCENTEBYNAMEREQUEST']._serialized_start=588
  _globals['_GETDOCENTEBYNAMEREQUEST']._serialized_end=638
  _globals['_ALUMNOSSERVICE']._serialized_start=641
  _globals['_ALUMNOSSERVICE']._serialized_end=1064
# @@protoc_insertion_point(module_scope)
