# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asistencias.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'asistencias.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61sistencias.proto\x12\x0f\x61gm.asistencias\"C\n\x1aGetAsistenciaAlumnoRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\"e\n\x0e\x41sistenciaItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tsesion_id\x18\x02 \x01(\t\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\x12\x15\n\rhora_registro\x18\x04 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x05 \x01(\t\"\xeb\x01\n\x19\x41sistenciasAlumnoResponse\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\x12\x14\n\x0ctotal_clases\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_presentes\x18\x04 \x01(\x05\x12\x16\n\x0etotal_retardos\x18\x05 \x01(\x05\x12\x16\n\x0etotal_ausentes\x18\x06 \x01(\x05\x12\x12\n\nporcentaje\x18\x07 \x01(\x02\x12\x34\n\x0b\x61sistencias\x18\x08 \x03(\x0b\x32\x1f.agm.asistencias.AsistenciaItem\"6\n GetEstadisticasAsistenciaRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"\xb1\x01\n\x1e\x45stadisticasAsistenciaResponse\x12\x12\n\nmateria_id\x18\x01 \x01(\t\x12\x16\n\x0etotal_sesiones\x18\x02 \x01(\x05\x12\x17\n\x0ftotal_registros\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_presentes\x18\x04 \x01(\x05\x12\x16\n\x0etotal_retardos\x18\x05 \x01(\x05\x12\x19\n\x11porcentaje_global\x18\x06 \x01(\x02\x32\x85\x02\n\x12\x41sistenciasService\x12n\n\x13GetAsistenciaAlumno\x12+.agm.asistencias.GetAsistenciaAlumnoRequest\x1a*.agm.asistencias.AsistenciasAlumnoResponse\x12\x7f\n\x19GetEstadisticasAsistencia\x12\x31.agm.asistencias.GetEstadisticasAsistenciaRequest\x1a/.agm.asistencias.EstadisticasAsistenciaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asistencias_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETASISTENCIAALUMNOREQUEST']._serialized_start=38
  _globals['_GETASISTENCIAALUMNOREQUEST']._serialized_end=105
  _globals['_ASISTENCIAITEM']._serialized_start=107
  _globals['_ASISTENCIAITEM']._serialized_end=208
  _globals['_ASISTENCIASALUMNORESPONSE']._serialized_start=211
  _globals['_ASISTENCIASALUMNORESPONSE']._serialized_end=446
  _globals['_GETESTADISTICASASISTENCIAREQUEST']._serialized_start=448
  _globals['_GETESTADISTICASASISTENCIAREQUEST']._serialized_end=502
  _globals['_ESTADISTICASASISTENCIARESPONSE']._serialized_start=505
  _globals['_ESTADISTICASASISTENCIARESPONSE']._serialized_end=682
  _globals['_ASISTENCIASSERVICE']._serialized_start=685
  _globals['_ASISTENCIASSERVICE']._serialized_end=946
# @@protoc_insertion_point(module_scope)
