# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/asistencias.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/asistencias.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/asistencias.proto\x12\x0b\x61sistencias\"C\n\x1aGetAsistenciaAlumnoRequest\x12\x11\n\talumno_id\x18\x01 \x01(\x05\x12\x12\n\nmateria_id\x18\x02 \x01(\x05\"e\n\x0e\x41sistenciaItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tsesion_id\x18\x02 \x01(\t\x12\x0e\n\x06\x65stado\x18\x03 \x01(\t\x12\x15\n\rhora_registro\x18\x04 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x05 \x01(\t\"\xe6\x01\n\x18\x41sistenciaAlumnoResponse\x12\x11\n\talumno_id\x18\x01 \x01(\x05\x12\x12\n\nmateria_id\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_clases\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_presentes\x18\x04 \x01(\x05\x12\x16\n\x0etotal_retardos\x18\x05 \x01(\x05\x12\x16\n\x0etotal_ausentes\x18\x06 \x01(\x05\x12\x12\n\nporcentaje\x18\x07 \x01(\x02\x12\x30\n\x0b\x61sistencias\x18\x08 \x03(\x0b\x32\x1b.asistencias.AsistenciaItem\",\n\x16GetEstadisticasRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\x05\"\xa7\x01\n\x14\x45stadisticasResponse\x12\x12\n\nmateria_id\x18\x01 \x01(\x05\x12\x16\n\x0etotal_sesiones\x18\x02 \x01(\x05\x12\x17\n\x0ftotal_registros\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_presentes\x18\x04 \x01(\x05\x12\x16\n\x0etotal_retardos\x18\x05 \x01(\x05\x12\x19\n\x11porcentaje_global\x18\x06 \x01(\x02\x32\xe0\x01\n\x12\x41sistenciasService\x12\x65\n\x13GetAsistenciaAlumno\x12\'.asistencias.GetAsistenciaAlumnoRequest\x1a%.asistencias.AsistenciaAlumnoResponse\x12\x63\n\x19GetEstadisticasAsistencia\x12#.asistencias.GetEstadisticasRequest\x1a!.asistencias.EstadisticasResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.asistencias_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETASISTENCIAALUMNOREQUEST']._serialized_start=40
  _globals['_GETASISTENCIAALUMNOREQUEST']._serialized_end=107
  _globals['_ASISTENCIAITEM']._serialized_start=109
  _globals['_ASISTENCIAITEM']._serialized_end=210
  _globals['_ASISTENCIAALUMNORESPONSE']._serialized_start=213
  _globals['_ASISTENCIAALUMNORESPONSE']._serialized_end=443
  _globals['_GETESTADISTICASREQUEST']._serialized_start=445
  _globals['_GETESTADISTICASREQUEST']._serialized_end=489
  _globals['_ESTADISTICASRESPONSE']._serialized_start=492
  _globals['_ESTADISTICASRESPONSE']._serialized_end=659
  _globals['_ASISTENCIASSERVICE']._serialized_start=662
  _globals['_ASISTENCIASSERVICE']._serialized_end=886
# @@protoc_insertion_point(module_scope)
