# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/calificaciones.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/calificaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/calificaciones.proto\x12\x0e\x63\x61lificaciones\"&\n\x10MateriaIdRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"=\n\x14\x41lumnoMateriaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\"k\n\x0b\x41lumnoCalif\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x15\n\ralumno_nombre\x18\x02 \x01(\t\x12\x15\n\rpromedio_real\x18\x03 \x01(\x01\x12\x1b\n\x13promedio_redondeado\x18\x04 \x01(\x05\"o\n\x13\x43oncentradoResponse\x12\x12\n\nmateria_id\x18\x01 \x01(\t\x12\x16\n\x0emateria_nombre\x18\x02 \x01(\t\x12,\n\x07\x61lumnos\x18\x03 \x03(\x0b\x32\x1b.calificaciones.AlumnoCalif\"F\n\x10PromedioResponse\x12\x15\n\rpromedio_real\x18\x01 \x01(\x01\x12\x1b\n\x13promedio_redondeado\x18\x02 \x01(\x05\"r\n\rStatsResponse\x12\x16\n\x0epromedio_grupo\x18\x01 \x01(\x01\x12\x18\n\x10\x63\x61lificacion_max\x18\x02 \x01(\x01\x12\x18\n\x10\x63\x61lificacion_min\x18\x03 \x01(\x01\x12\x15\n\rtotal_alumnos\x18\x04 \x01(\x05\x32\xa8\x02\n\x15\x43\x61lificacionesService\x12W\n\x0eGetConcentrado\x12 .calificaciones.MateriaIdRequest\x1a#.calificaciones.ConcentradoResponse\x12[\n\x11GetPromedioAlumno\x12$.calificaciones.AlumnoMateriaRequest\x1a .calificaciones.PromedioResponse\x12Y\n\x16GetEstadisticasMateria\x12 .calificaciones.MateriaIdRequest\x1a\x1d.calificaciones.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.calificaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATERIAIDREQUEST']._serialized_start=46
  _globals['_MATERIAIDREQUEST']._serialized_end=84
  _globals['_ALUMNOMATERIAREQUEST']._serialized_start=86
  _globals['_ALUMNOMATERIAREQUEST']._serialized_end=147
  _globals['_ALUMNOCALIF']._serialized_start=149
  _globals['_ALUMNOCALIF']._serialized_end=256
  _globals['_CONCENTRADORESPONSE']._serialized_start=258
  _globals['_CONCENTRADORESPONSE']._serialized_end=369
  _globals['_PROMEDIORESPONSE']._serialized_start=371
  _globals['_PROMEDIORESPONSE']._serialized_end=441
  _globals['_STATSRESPONSE']._serialized_start=443
  _globals['_STATSRESPONSE']._serialized_end=557
  _globals['_CALIFICACIONESSERVICE']._serialized_start=560
  _globals['_CALIFICACIONESSERVICE']._serialized_end=856
# @@protoc_insertion_point(module_scope)
