# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import periodos_pb2 as periodos__pb2


class PeriodosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMateriaById = channel.unary_unary(
                '/periodos.PeriodosService/GetMateriaById',
                request_serializer=periodos__pb2.MateriaIdRequest.SerializeToString,
                response_deserializer=periodos__pb2.MateriaInfo.FromString,
                )
        self.GetMateriasByDocente = channel.unary_unary(
                '/periodos.PeriodosService/GetMateriasByDocente',
                request_serializer=periodos__pb2.DocenteIdRequest.SerializeToString,
                response_deserializer=periodos__pb2.MateriasListResponse.FromString,
                )
        self.GetPeriodoActivo = channel.unary_unary(
                '/periodos.PeriodosService/GetPeriodoActivo',
                request_serializer=periodos__pb2.Empty.SerializeToString,
                response_deserializer=periodos__pb2.PeriodoInfo.FromString,
                )


class PeriodosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMateriaById(self, request, context):
        """MS-2 Periodos & Materias logic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMateriasByDocente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeriodoActivo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeriodosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMateriaById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriaById,
                    request_deserializer=periodos__pb2.MateriaIdRequest.FromString,
                    response_serializer=periodos__pb2.MateriaInfo.SerializeToString,
            ),
            'GetMateriasByDocente': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateriasByDocente,
                    request_deserializer=periodos__pb2.DocenteIdRequest.FromString,
                    response_serializer=periodos__pb2.MateriasListResponse.SerializeToString,
            ),
            'GetPeriodoActivo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeriodoActivo,
                    request_deserializer=periodos__pb2.Empty.FromString,
                    response_serializer=periodos__pb2.PeriodoInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'periodos.PeriodosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PeriodosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMateriaById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/periodos.PeriodosService/GetMateriaById',
            periodos__pb2.MateriaIdRequest.SerializeToString,
            periodos__pb2.MateriaInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMateriasByDocente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/periodos.PeriodosService/GetMateriasByDocente',
            periodos__pb2.DocenteIdRequest.SerializeToString,
            periodos__pb2.MateriasListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPeriodoActivo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/periodos.PeriodosService/GetPeriodoActivo',
            periodos__pb2.Empty.SerializeToString,
            periodos__pb2.PeriodoInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
