# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/reportes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/reportes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/reportes.proto\x12\x08reportes\"R\n\x15GenerateReportRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\x12\x14\n\x0ctipo_reporte\x18\x02 \x01(\t\x12\x0f\n\x07\x66ormato\x18\x03 \x01(\t\",\n\x16GenerateReportResponse\x12\x12\n\nfile_bytes\x18\x01 \x01(\x0c\"-\n\x17HistorialDocenteRequest\x12\x12\n\ndocente_id\x18\x01 \x01(\t\"\x97\x01\n\x0cStatsPeriodo\x12\x12\n\nperiodo_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\x12\x16\n\x0epromedio_grupo\x18\x03 \x01(\x02\x12\x17\n\x0ftasa_asistencia\x18\x04 \x01(\x02\x12\x17\n\x0ftasa_aprobacion\x18\x05 \x01(\x02\x12\x15\n\rtotal_alumnos\x18\x06 \x01(\x05\"E\n\x18HistorialDocenteResponse\x12)\n\thistorial\x18\x01 \x03(\x0b\x32\x16.reportes.StatsPeriodo2\xc4\x01\n\x0fReportesService\x12S\n\x0eGenerateReport\x12\x1f.reportes.GenerateReportRequest\x1a .reportes.GenerateReportResponse\x12\\\n\x13GetHistorialDocente\x12!.reportes.HistorialDocenteRequest\x1a\".reportes.HistorialDocenteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.reportes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREPORTREQUEST']._serialized_start=34
  _globals['_GENERATEREPORTREQUEST']._serialized_end=116
  _globals['_GENERATEREPORTRESPONSE']._serialized_start=118
  _globals['_GENERATEREPORTRESPONSE']._serialized_end=162
  _globals['_HISTORIALDOCENTEREQUEST']._serialized_start=164
  _globals['_HISTORIALDOCENTEREQUEST']._serialized_end=209
  _globals['_STATSPERIODO']._serialized_start=212
  _globals['_STATSPERIODO']._serialized_end=363
  _globals['_HISTORIALDOCENTERESPONSE']._serialized_start=365
  _globals['_HISTORIALDOCENTERESPONSE']._serialized_end=434
  _globals['_REPORTESSERVICE']._serialized_start=437
  _globals['_REPORTESSERVICE']._serialized_end=633
# @@protoc_insertion_point(module_scope)
