# Generated by Django 5.2.1 on 2026-05-08 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('tipo_formacion', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_acceso', models.CharField(blank=True, help_text='Clave generada al registrarse', max_length=255, null=True)),
                ('user_id', models.UUIDField(blank=True, help_text='Referencia lógica al MS-1 Auth', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumnos',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo_institucional', models.EmailField(max_length=255, unique=True)),
                ('cubiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.UUIDField(blank=True, help_text='Referencia lógica al MS-1 Auth', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
                'db_table': 'docentes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia_id', models.UUIDField(help_text='Referencia lógica al MS-2 Periodos')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='models.alumno')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripciones',
            },
        ),
        UnaccentExtension(),
    ]
