# Generated by Django 4.2.16 on 2026-05-28 06:24
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoReplica',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_completo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'replica_alumnos',
            },
        ),
        migrations.CreateModel(
            name='MateriaReplica',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nrc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'replica_materias',
            },
        ),
    ]