# Generated by Django 5.2.14 on 2026-05-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_add_requires_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
