# Generated by Django 6.0.5 on 2026-05-21 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('seccion', models.CharField(blank=True, max_length=10, null=True)),
                ('docente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('docente_id', models.UUIDField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('finalizada', 'Finalizada')], default='abierta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('plan_estudios', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=5)),
                ('hora_inicio', models.CharField(blank=True, max_length=4, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=4, null=True)),
                ('salon', models.CharField(blank=True, max_length=20, null=True)),
                ('es_virtual', models.BooleanField(default=False)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.materia')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='api.periodo'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(fields=('nrc', 'periodo'), name='unique_nrc_per_periodo'),
        ),
    ]
