# Generated by Django 5.2.1 on 2026-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='campus',
            field=models.CharField(choices=[('CU2', 'Campus CU2'), ('SAN_MANUEL', 'Campus CU San Manuel')], default='SAN_MANUEL', max_length=20),
        ),
    ]
