# Generated by Django 5.2.1 on 2026-05-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_periodo_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={},
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='plan_estudios',
        ),
        migrations.AddField(
            model_name='materia',
            name='campus',
            field=models.CharField(choices=[('CU2', 'Campus CU2'), ('SAN_MANUEL', 'Campus CU San Manuel')], default='SAN_MANUEL', max_length=20),
        ),
        migrations.AddField(
            model_name='materia',
            name='plan_estudios',
            field=models.CharField(default='ITI', max_length=50),
        ),
    ]
