# Generated by Django 5.2.1 on 2026-05-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_periodo_options_remove_periodo_campus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='activo',
        ),
        migrations.AddField(
            model_name='periodo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20),
        ),
    ]
