syntax = "proto3";

package agm.asistencias;

service AsistenciasService {
    rpc GetAsistenciaAlumno(GetAsistenciaAlumnoRequest) returns (AsistenciasAlumnoResponse);
    rpc GetEstadisticasAsistencia(GetEstadisticasAsistenciaRequest) returns (EstadisticasAsistenciaResponse);
}

message GetAsistenciaAlumnoRequest {
    string alumno_id  = 1;
    string materia_id = 2;
}

message AsistenciaItem {
    string id             = 1;
    string sesion_id      = 2;
    string estado         = 3;
    string hora_registro  = 4;
    string fecha          = 5;
}

message AsistenciasAlumnoResponse {
    string alumno_id       = 1;
    string materia_id      = 2;
    int32  total_clases    = 3;
    int32  total_presentes = 4;
    int32  total_retardos  = 5;
    int32  total_ausentes  = 6;
    float  porcentaje      = 7;
    repeated AsistenciaItem asistencias = 8;
}

message GetEstadisticasAsistenciaRequest {
    string materia_id = 1;
}

message EstadisticasAsistenciaResponse {
    string materia_id        = 1;
    int32  total_sesiones    = 2;
    int32  total_registros   = 3;
    int32  total_presentes   = 4;
    int32  total_retardos    = 5;
    float  porcentaje_global = 6;
}