# Generated by Django 5.1 on 2026-05-21 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPonderacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'categoria_ponderacion',
            },
        ),
        migrations.CreateModel(
            name='PonderacionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia_id', models.UUIDField(unique=True)),
                ('bloqueada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ponderacion_config',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='actividades', to='models.categoriaponderacion')),
            ],
            options={
                'db_table': 'actividad',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='categoriaponderacion',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='models.ponderacionconfig'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alumno_id', models.UUIDField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='calificaciones', to='models.actividad')),
            ],
            options={
                'db_table': 'calificacion',
                'constraints': [models.UniqueConstraint(fields=('actividad', 'alumno_id'), name='unique_calificacion_por_alumno_actividad')],
            },
        ),
    ]
