# Generated by Django 5.1 on 2026-05-26 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia_id', models.UUIDField()),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ponderacion',
                'ordering': ['orden', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('materia_id', 'nombre_categoria'), name='unique_activa_ponderacion_nombre_materia')],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ponderacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='actividades', to='models.ponderacion')),
            ],
            options={
                'db_table': 'actividad',
                'ordering': ['orden', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alumno_id', models.UUIDField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuente', models.CharField(choices=[('manual', 'Captura manual'), ('importada', 'Importación masiva')], default='manual', max_length=10)),
                ('observacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='calificaciones', to='models.actividad')),
            ],
            options={
                'db_table': 'calificacion',
                'constraints': [models.UniqueConstraint(fields=('actividad', 'alumno_id'), name='unique_calificacion_por_alumno_actividad')],
            },
        ),
    ]
