# Generated by Django 5.1 on 2026-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='fuente',
            field=models.CharField(choices=[('manual', 'Captura manual'), ('importada', 'Importación masiva')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
