# Generated by Django 5.1 on 2026-05-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_add_fuente_observacion_to_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
