# Generated by Django 6.0.5 on 2026-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('baja', 'Baja de Materia'), ('cierre', 'Cierre de Materia'), ('reset', 'Recuperación de Contraseña')], max_length=20)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(default='pendiente', max_length=15)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_log',
            },
        ),
    ]
