# Generated by Django 6.0.5 on 2026-05-25 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('baja', 'Baja'), ('cierre', 'Cierre de Materia'), ('reset_password', 'Recuperación de Contraseña')], max_length=50)),
                ('destinatario_email', models.EmailField(max_length=255)),
                ('destinatario_id', models.UUIDField(blank=True, null=True)),
                ('asunto', models.CharField(max_length=255)),
                ('contenido', models.TextField(help_text='Cuerpo del correo (HTML renderizado)')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales (materiaId, docenteId, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificaciones_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
