# Generated by Django 6.0.5 on 2026-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationlog',
            old_name='mensaje',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='notificationlog',
            old_name='fecha_envio',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='destinatario_email',
            field=models.EmailField(default='angel.aguilarsal@alumno.buap.mx', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='destinatario_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error_detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='tipo',
            field=models.CharField(choices=[('bienvenida', 'Bienvenida'), ('baja', 'Baja de Materia'), ('cierre', 'Cierre de Materia'), ('reset_password', 'Recuperación de Contraseña')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='notificationlog',
            table='notificaciones_log',
        ),
    ]
