# Generated by Django 6.0.5 on 2026-05-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='tipo',
            field=models.CharField(choices=[('bienvenida', 'Bienvenida'), ('baja', 'Baja'), ('cierre', 'Cierre de Materia'), ('reset_password', 'Recuperación de Contraseña'), ('reporte_finalizado', 'Reporte Académico Finalizado')], max_length=50),
        ),
    ]
