# Generated by Django 6.0.5 on 2026-05-24 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_mensaje_notificationlog_contenido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='contenido',
            field=models.TextField(help_text='Cuerpo del correo (HTML renderizado)'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='destinatario_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales (materiaId, docenteId, etc.)'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='tipo',
            field=models.CharField(choices=[('bienvenida', 'Bienvenida'), ('baja', 'Baja'), ('cierre', 'Cierre de Materia'), ('reset_password', 'Recuperación de Contraseña')], max_length=50),
        ),
    ]
