# Generated by Django 5.1 on 2026-05-07 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PonderacionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia_id', models.UUIDField(unique=True)),
                ('bloqueada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ponderacion_config',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPonderacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='ponderaciones.ponderacionconfig')),
            ],
            options={
                'db_table': 'categoria_ponderacion',
            },
        ),
    ]
