# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notificaciones.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notificaciones.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14notificaciones.proto\x12\x12\x61gm.notificaciones\":\n\x11\x42ienvenidaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\nmateria_id\x18\x02 \x01(\t\"4\n\x0b\x42\x61jaRequest\x12\x11\n\talumno_id\x18\x01 \x01(\t\x12\x12\n\ndocente_id\x18\x02 \x01(\t\"#\n\rCierreRequest\x12\x12\n\nmateria_id\x18\x01 \x01(\t\"\x1f\n\x0c\x42oolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa0\x02\n\x15NotificacionesService\x12Y\n\x0eSendBienvenida\x12%.agm.notificaciones.BienvenidaRequest\x1a .agm.notificaciones.BoolResponse\x12R\n\rSendBajaNotif\x12\x1f.agm.notificaciones.BajaRequest\x1a .agm.notificaciones.BoolResponse\x12X\n\x11SendCierreMateria\x12!.agm.notificaciones.CierreRequest\x1a .agm.notificaciones.BoolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notificaciones_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIENVENIDAREQUEST']._serialized_start=44
  _globals['_BIENVENIDAREQUEST']._serialized_end=102
  _globals['_BAJAREQUEST']._serialized_start=104
  _globals['_BAJAREQUEST']._serialized_end=156
  _globals['_CIERREREQUEST']._serialized_start=158
  _globals['_CIERREREQUEST']._serialized_end=193
  _globals['_BOOLRESPONSE']._serialized_start=195
  _globals['_BOOLRESPONSE']._serialized_end=226
  _globals['_NOTIFICACIONESSERVICE']._serialized_start=229
  _globals['_NOTIFICACIONESSERVICE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
